### ISSUE TITLE
Перестает отвечать интеграция SMS notifications via GSM-modem после звонка

### ISSUE THREAD

**Issue by dante1613** [black-roland/homeassistant-gsm-call#3]
Спасибо за интеграцию, интересные возможности для ее применения.

И по теме проблемы. После звонка через `notify.call`, встроенная интеграция [SMS notifications via GSM-modem](https://www.home-assistant.io/integrations/sms/) отваливается с ошибками до момента пока не перезапустишь home assistant, при этом ваша интеграция продолжает работать, можно повторять звонки. Бывает что **SMS notifications via GSM-modem** снова подниметься, но это если один звонок сделать, а от если 2 подряд то не стартует (минут 20 ждал).

```
2024-09-16 16:37:10.772 ERROR (MainThread) [homeassistant.components.sms.coordinator] Timeout fetching Device signal state data
2024-09-16 16:37:10.950 ERROR (MainThread) [homeassistant.components.sms.coordinator] Timeout fetching Device network state data
```

Использованное оборудование и настройки:

1. Модем: **ZTE MF192** с прошивкой [BD_MF190BV1.0.0B04](https://3ginfo.ru/downloads2139.html) в режиме **Модем+CD ROM**.

2. Хост: мини пк с proxmox, на котором крутиться HAOS и полностью прокинут USB порт. HAOS видит 4 интерфейса + отдельно CD ROM

<details>
  <summary>Интерфейсы</summary>

  ```
$ ls -1 /dev/serial/by-id/usb-ZTE_MF190B_2A830CAA59B7675CD21B6F3AA65C39BA3B50245B-if0*
/dev/serial/by-id/usb-ZTE_MF190B_2A830CAA59B7675CD21B6F3AA65C39BA3B50245B-if01
/dev/serial/by-id/usb-ZTE_MF190B_2A830CAA59B7675CD21B6F3AA65C39BA3B50245B-if03
/dev/serial/by-id/usb-ZTE_MF190B_2A830CAA59B7675CD21B6F3AA65C39BA3B50245B-if05
/dev/serial/by-id/usb-ZTE_MF190B_2A830CAA59B7675CD21B6F3AA65C39BA3B50245B-if07
  ```
  
</details>

Для SMS интеграции используется порт: `/dev/serial/by-id/usb-ZTE_MF190B_2A830CAA59B7675CD21B6F3AA65C39BA3B50245B-if01`

Для интеграции звонков: `/dev/serial/by-id/usb-ZTE_MF190B_2A830CAA59B7675CD21B6F3AA65C39BA3B50245B-if03`

Перепробовал все порты, с 01 и 03 нормально работает, с 05 никак не реагирует.

С 07 виснет дашбоард HA, пока не перезагрузишь саму виртуальную машину, при этом по SSH доступ есть, в логе в момент зависания пишет `Dialing +380951234567...`, но это не так важно, главное что с 03 работает (вместе на одном порту тоже работает, к примеру 01, но так же смс отваливается)

Прописал в `configuration.yaml` вывод логов `custom_components.gsm_call: debug`, но пользы это не дало в плане дополнительной информации, интеграция звонков продолжает работать, отваливается именно SMS. Если звонки не совершать, то SMS нормально работают, отсылаются, принимаются, перезагрузок или отваливаний нет. Так же не помогает перезагрузка интеграции через GUI и через службу  `homeassistant.reload_config_entry`, когда уже произошел отвал

Логи после совершения звонка

<details>
  <summary>Лог</summary>

  ```
2024-09-16 16:36:15.211 DEBUG (MainThread) [custom_components.gsm_call.notify] Connecting to /dev/serial/by-id/usb-ZTE_MF190B_2A830CAA59B7675CD21B6F3AA65C39BA3B50245B-if03...
2024-09-16 16:36:15.238 DEBUG (MainThread) [custom_components.gsm_call.notify] Dialing +380951234567...
2024-09-16 16:36:16.243 DEBUG (MainThread) [custom_components.gsm_call.notify] Modem replied with $ATD+380951234567;

OK

2024-09-16 16:36:16.243 INFO (MainThread) [custom_components.gsm_call.notify] Ringing for 30 seconds...
2024-09-16 16:36:46.245 DEBUG (MainThread) [custom_components.gsm_call.notify] Hanging up...
2024-09-16 16:36:46.248 DEBUG (MainThread) [custom_components.gsm_call.notify] Closing connection to the modem...
2024-09-16 16:37:10.772 ERROR (MainThread) [homeassistant.components.sms.coordinator] Timeout fetching Device signal state data
2024-09-16 16:37:10.950 ERROR (MainThread) [homeassistant.components.sms.coordinator] Timeout fetching Device network state data
2024-09-16 16:37:51.793 DEBUG (MainThread) [custom_components.gsm_call.notify] Connecting to /dev/serial/by-id/usb-ZTE_MF190B_2A830CAA59B7675CD21B6F3AA65C39BA3B50245B-if03...
2024-09-16 16:37:51.797 DEBUG (MainThread) [custom_components.gsm_call.notify] Dialing +380951234567...
2024-09-16 16:37:52.804 DEBUG (MainThread) [custom_components.gsm_call.notify] Modem replied with $ATD+380951234567;

OK

2024-09-16 16:37:52.805 INFO (MainThread) [custom_components.gsm_call.notify] Ringing for 30 seconds...
2024-09-16 16:38:22.806 DEBUG (MainThread) [custom_components.gsm_call.notify] Hanging up...
2024-09-16 16:38:22.809 DEBUG (MainThread) [custom_components.gsm_call.notify] Closing connection to the modem...



// Видимо тут модем пытается оживать, но тщетно


Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.105 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'CID': '01369ADD', 'GPRS': 'Attached', 'LAC': 'EAEA', 'NetworkCode': '255 03', ...}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.112 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'BitErrorRate': 0, 'SignalPercent': 42, 'SignalStrength': -85}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.132 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'CID': '01369ADD', 'GPRS': 'Attached', 'LAC': 'EAEA', 'NetworkCode': '255 03', ...}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.137 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'BitErrorRate': 0, 'SignalPercent': 42, 'SignalStrength': -85}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.156 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'CID': '01369ADD', 'GPRS': 'Attached', 'LAC': 'EAEA', 'NetworkCode': '255 03', ...}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.160 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'BitErrorRate': 0, 'SignalPercent': 42, 'SignalStrength': -85}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.182 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'CID': '01369ADD', 'GPRS': 'Attached', 'LAC': 'EAEA', 'NetworkCode': '255 03', ...}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.186 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'BitErrorRate': 0, 'SignalPercent': 42, 'SignalStrength': -85}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.208 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'CID': '01369ADD', 'GPRS': 'Attached', 'LAC': 'EAEA', 'NetworkCode': '255 03', ...}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.215 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'BitErrorRate': 0, 'SignalPercent': 42, 'SignalStrength': -85}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.233 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'CID': '01369ADD', 'GPRS': 'Attached', 'LAC': 'EAEA', 'NetworkCode': '255 03', ...}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.237 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'BitErrorRate': 0, 'SignalPercent': 42, 'SignalStrength': -85}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.258 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'CID': '01369ADD', 'GPRS': 'Attached', 'LAC': 'EAEA', 'NetworkCode': '255 03', ...}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.267 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'BitErrorRate': 0, 'SignalPercent': 42, 'SignalStrength': -85}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.290 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result({'CID': '01369ADD', 'GPRS': 'Attached', 'LAC': 'EAEA', 'NetworkCode': '255 03', ...}) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
2024-09-16 16:45:15.301 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result(None) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
  ```
  
</details>

Посмотрел у вас в коде прописан `baudrate=75600`, для интеграции SMS я выбирал `115200`, думал причина в этом, пытался поменять в интеграции SMS, но там ближайшее только `76800` (с этим значением не дает добавить модем), по этому через редактор отредактировал файл (в вашей интеграции) `notify.py` поменяв на `115200` и перезапустил HA, но эффекта это не дало, все также отваливается SMS интеграция. Если поменять в самой интеграции SMS путем редактирования `core.config_entries` на `75600` и перезапустить, модем тогда так же не стартует. Пока что вернул все значения обратно (115200 для SMS и 75600 для звонков) и вызовами не пользуюсь

**Comment by dante1613** [comment]
Ради интереса создал виртуальную машину в Vmvare Workstation Pro с Debian 12, поставил supervised версию home assistant и восстановил бекап с основного сервера home assistant.

После подключения модема отключил [ModemManager](https://askubuntu.com/questions/216114/how-can-i-remove-modem-manager-from-boot/612646) (так как в HAOS его нет, думал в нем причина) и далее прописал такие же порты для SMS интеграции (01) и для звонков (03). Но результат тот же самый, после совершения звонка сразу же отваливается SMS интеграция

Еще пробовал делать вызов как через команду `ATD`, так и через `ATDT`, работает с любой командой, но отвал все равно происходит

**Comment by black-roland** [comment]
Ох, сложно что-то здесь порекомендовать. Есть ли возможность откатить интеграцию на версию [v0.1.2](https://github.com/black-roland/homeassistant-gsm-call/releases/tag/v0.1.2)?

В последней версии я добавил парсинг ответов от модема, а раньше интеграция просто отправляла команду на дозвон и отключалась. Теперь я боюсь, что из-за последних изменений совместимость с интеграцией SMS поломалась.

Но вообще судя по логам там что-то странное происходит :slightly_smiling_face: Интеграция SMS вроде как продолжает нормально взаимодействовать с модемом, но падает при попытке обновить состояние.

**Comment by dante1613** [comment]
Удалил 0.1.3 версию и при попытке поставить 0.1.2 пишет что не может быть использована с HACS

![image](https://github.com/user-attachments/assets/ee93cfe6-1292-4bfd-beb6-e47650bc6c4e)

**Comment by dante1613** [comment]
Поставил обратно 0.1.3 через HACS и просто вручную заменил файлы с версии 0.1.2
Но все так же отваливается
```
2024-09-18 01:08:16.064 INFO (MainThread) [custom_components.gsm_call.notify] Connecting to /dev/serial/by-id/usb-ZTE_MF190B_2A830CAA59B7675CD21B6F3AA65C39BA3B50245B-if03...
2024-09-18 01:08:16.074 DEBUG (MainThread) [custom_components.gsm_call.notify] Dialing 380951234567...
2024-09-18 01:08:16.076 DEBUG (MainThread) [custom_components.gsm_call.notify] ATD sent
2024-09-18 01:08:51.078 INFO (MainThread) [custom_components.gsm_call.notify] Hanging up...
2024-09-18 01:09:05.400 ERROR (MainThread) [homeassistant.components.sms.coordinator] Timeout fetching Device signal state data
2024-09-18 01:09:05.460 ERROR (MainThread) [homeassistant.components.sms.coordinator] Timeout fetching Device network state data
```

**Comment by black-roland** [comment]
Не имея такого же модема на руках я, к сожалению, вряд ли смогу помочь :slightly_frowning_face:

Но я бы попробовал удалить вот эти строчки:

```diff
--- a/custom_components/gsm_call/notify.py
+++ b/custom_components/gsm_call/notify.py
@@ -92,9 +92,5 @@ class GsmCallNotificationService(BaseNotificationService):
         modem.write(f'{self.at_command}+{phone_number};\r\n'.encode())
         _LOGGER.debug(f"{self.at_command} sent")
 
-        await asyncio.sleep(self.call_duration + 10)
-
-        _LOGGER.info("Hanging up...")
-        modem.write(b'AT+CHUP\r\n')
         modem.close()
         GsmCallNotificationService.lock = False
```

Не уверен, что это поможет. Просто для того, чтобы положить трубку, существует 2 команды: `ATH` и `AT+CHUP`. Если вдруг по какой-то причине все ломается из-за `AT+CHUP`, то удаление этих строчек поможет.
